export interface CustomAsset {
    company_name?: string;
    company_id?: number;
    location?: string;
    location_id?: number;
    default_location?: string;
    department?: string;
    department_id?: number;
    supplier?: string;
    supplier_id?: number;
    model?: string;
    asset_model_id?: number;
    manufacturer?: string;
    manufacturer_id?: number;
    category?: string;
    category_id?: number;
    status?: string;
    status_id?: number;
    status_name?: string;
    status_created_at?: string;
    status_labels?: {
        created_at?: string;
        id?: number;
        name?: string;
    }
    order_number?: string;
    pruchase_date_from?: string;
    pruchase_date_to?: string;
    created_at_from?: string;
    created_at_to?: string;
    checkout_from?: string;
    checkout_to?: string;
    last_checkin_from?: string;
    last_checkin_to?: string;
    expected_checkin_from?: string;
    expected_checkin_to?: string;
    eol_from?: string;
    eol_to?: string;
    last_audit_from?: string;
    last_audit_to?: string;
    next_audit_from?: string;
    next_audit_to?: string;
    archived_assets?: string;
    deleted_assets?: string;
}